// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class Material
    {
        [DataMember(Name = "id")]
        public byte Id;
        [DataMember(Name = "name")]
        public string Name;
        [DataMember(Name = "description")]
        public string Description;
        [DataMember(Name = "density")]
        public float Density;

        public Material(
            byte Id,
            string Name,
            string Description,
            float Density
        )
        {
            this.Id = Id;
            this.Name = Name;
            this.Description = Description;
            this.Density = Density;
        }

        public Material()
        {
            this.Name = "";
            this.Description = "";
        }
    }
}
