// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class Mob
    {
        [DataMember(Name = "id")]
        public ulong Id;
        [DataMember(Name = "chunk_id")]
        public ulong ChunkId;
        [DataMember(Name = "pos_x")]
        public float PosX;
        [DataMember(Name = "pos_y")]
        public float PosY;
        [DataMember(Name = "pos_z")]
        public float PosZ;
        [DataMember(Name = "vel_azi")]
        public float VelAzi;
        [DataMember(Name = "vel_rot")]
        public float VelRot;
        [DataMember(Name = "vel_mag")]
        public float VelMag;

        public Mob(
            ulong Id,
            ulong ChunkId,
            float PosX,
            float PosY,
            float PosZ,
            float VelAzi,
            float VelRot,
            float VelMag
        )
        {
            this.Id = Id;
            this.ChunkId = ChunkId;
            this.PosX = PosX;
            this.PosY = PosY;
            this.PosZ = PosZ;
            this.VelAzi = VelAzi;
            this.VelRot = VelRot;
            this.VelMag = VelMag;
        }

        public Mob()
        {
        }
    }
}
