// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class NodeData
    {
        [DataMember(Name = "id")]
        public ulong Id;
        [DataMember(Name = "chunk_id")]
        public ulong ChunkId;
        [DataMember(Name = "x")]
        public byte X;
        [DataMember(Name = "y")]
        public byte Y;
        [DataMember(Name = "z")]
        public byte Z;
        [DataMember(Name = "contents")]
        public System.Collections.Generic.List<byte> Contents;

        public NodeData(
            ulong Id,
            ulong ChunkId,
            byte X,
            byte Y,
            byte Z,
            System.Collections.Generic.List<byte> Contents
        )
        {
            this.Id = Id;
            this.ChunkId = ChunkId;
            this.X = X;
            this.Y = Y;
            this.Z = Z;
            this.Contents = Contents;
        }

        public NodeData()
        {
            this.Contents = new();
        }
    }
}
