// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class ChunkDataHandle : RemoteTableHandle<EventContext, ChunkData>
        {
            protected override string RemoteTableName => "chunk_data";

            public sealed class IdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(ChunkData row) => row.Id;

                public IdUniqueIndex(ChunkDataHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            public sealed class PositionIndex : BTreeIndexBase<(int X, int Y, int Z)>
            {
                protected override (int X, int Y, int Z) GetKey(ChunkData row) => (row.X, row.Y, row.Z);

                public PositionIndex(ChunkDataHandle table) : base(table) { }
            }

            public readonly PositionIndex Position;

            internal ChunkDataHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
                Position = new(this);
            }

            protected override object GetPrimaryKey(ChunkData row) => row.Id;
        }

        public readonly ChunkDataHandle ChunkData;
    }
}
