// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class MaterialsHandle : RemoteTableHandle<EventContext, Material>
        {
            protected override string RemoteTableName => "materials";

            public sealed class IdUniqueIndex : UniqueIndexBase<byte>
            {
                protected override byte GetKey(Material row) => row.Id;

                public IdUniqueIndex(MaterialsHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            internal MaterialsHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
            }

            protected override object GetPrimaryKey(Material row) => row.Id;
        }

        public readonly MaterialsHandle Materials;
    }
}
