// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class MobHandle : RemoteTableHandle<EventContext, Mob>
        {
            protected override string RemoteTableName => "mob";

            public sealed class IdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(Mob row) => row.Id;

                public IdUniqueIndex(MobHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            public sealed class PositionIndex : BTreeIndexBase<(float PosX, float PosY, float PosZ)>
            {
                protected override (float PosX, float PosY, float PosZ) GetKey(Mob row) => (row.PosX, row.PosY, row.PosZ);

                public PositionIndex(MobHandle table) : base(table) { }
            }

            public readonly PositionIndex Position;

            internal MobHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
                Position = new(this);
            }

            protected override object GetPrimaryKey(Mob row) => row.Id;
        }

        public readonly MobHandle Mob;
    }
}
