// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class NodeDataHandle : RemoteTableHandle<EventContext, NodeData>
        {
            protected override string RemoteTableName => "node_data";

            public sealed class PositionIndex : BTreeIndexBase<(ulong ChunkId, byte X, byte Y, byte Z)>
            {
                protected override (ulong ChunkId, byte X, byte Y, byte Z) GetKey(NodeData row) => (row.ChunkId, row.X, row.Y, row.Z);

                public PositionIndex(NodeDataHandle table) : base(table) { }
            }

            public readonly PositionIndex Position;

            public sealed class IdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(NodeData row) => row.Id;

                public IdUniqueIndex(NodeDataHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            internal NodeDataHandle(DbConnection conn) : base(conn)
            {
                Position = new(this);
                Id = new(this);
            }

            protected override object GetPrimaryKey(NodeData row) => row.Id;
        }

        public readonly NodeDataHandle NodeData;
    }
}
