// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void MakeNodeHandler(ReducerEventContext ctx);
        public event MakeNodeHandler? OnMakeNode;

        public void MakeNode()
        {
            conn.InternalCallReducer(new Reducer.MakeNode(), this.SetCallReducerFlags.MakeNodeFlags);
        }

        public bool InvokeMakeNode(ReducerEventContext ctx, Reducer.MakeNode args)
        {
            if (OnMakeNode == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnMakeNode(
                ctx
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class MakeNode : Reducer, IReducerArgs
        {
            string IReducerArgs.ReducerName => "make_node";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags MakeNodeFlags;
        public void MakeNode(CallReducerFlags flags) => MakeNodeFlags = flags;
    }
}
