// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void MakeChunkHandler(ReducerEventContext ctx);
        public event MakeChunkHandler? OnMakeChunk;

        public void MakeChunk()
        {
            conn.InternalCallReducer(new Reducer.MakeChunk(), this.SetCallReducerFlags.MakeChunkFlags);
        }

        public bool InvokeMakeChunk(ReducerEventContext ctx, Reducer.MakeChunk args)
        {
            if (OnMakeChunk == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnMakeChunk(
                ctx
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class MakeChunk : Reducer, IReducerArgs
        {
            string IReducerArgs.ReducerName => "make_chunk";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags MakeChunkFlags;
        public void MakeChunk(CallReducerFlags flags) => MakeChunkFlags = flags;
    }
}
